name: Balea continous Deployment (PREVIEW)
on:
  push:
    branches:
      - "release/*"

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      VERSION_SUFFIX: -preview${{ github.run_id }}
    name: Build
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: microsoft/mssql-server-linux
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!
        ports:
          - 5433:1433
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: dotnet build
        run: dotnet build Balea.sln -c $BUILD_CONFIG
      - name: dotnet test [FunctionalTests]
        run: dotnet test ./test/FunctionalTests/FunctionalTests.csproj -c $BUILD_CONFIG --no-build
      - name: dotnet pack [Balea]
        run: dotnet pack ./src/Balea/Balea.csproj -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols -o ./artifacts
      - name: dotnet pack [Balea.Configuration.Store]
        run: dotnet pack ./src/Balea.Configuration.Store/Balea.Configuration.Store.csproj -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols -o ./artifacts
      - name: dotnet pack [Balea.EntityFrameworkCore.Store]
        run: dotnet pack ./src/Balea.EntityFrameworkCore.Store/Balea.EntityFrameworkCore.Store.csproj -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols -o ./artifacts
      - name: setup nuget
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-version: latest
      - name: Publish Balea nuget
        run: dotnet nuget push ./artifacts/Balea.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish Configuration Store nuget
        run: dotnet nuget push ./artifacts/Balea.Configuration.Store.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish EntityFramework Store  nuget
        run: dotnet nuget push ./artifacts/Balea.EntityFrameworkCore.Store.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
